// Code generated by mfd-generator; DO NOT EDIT.

//nolint
//lint:file-ignore U1000 ignore unused code, it's generated
package db

const (
	ErrEmptyValue = "empty"
	ErrMaxLength  = "len"
	ErrWrongValue = "value"
)

func (n News) Validate() (errors map[string]string, valid bool) {
	errors = map[string]string{}

	if n.TagIDs == nil {
		errors[Columns.News.TagIDs] = ErrEmptyValue
	}

	return errors, len(errors) == 0
}
