version: "3"

services:
  pgsql:
    container_name: pgsql
    image: postgres:13.4-buster
    ports:
      - "5432:5432"
    volumes:
      - ./data/postgres/:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: news
      TZ: "Europe/Moscow"